config/routes.rb
Falgun::Application.routes.draw do

  resources :log_errors


  resources :logs


  devise_for :users

  root :to => "home#index"

  namespace :api do
    scope :module => 'v1', :constraints => ApiConstraints.new(:version => 1, :default => true) do
      resources :logs, :constraints => { :id => /.*/ }
    end
  end

end

app/models/log.rb
class Log
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, :type => String
  field :key, :type => String

  field :api_code, :type => String

  referenced_in   :user, :class_name => "User"

  validates_presence_of :user, :name
  validates_uniqueness_of :key

  validates_length_of :name, :in => 3..40

  validate :generate_api_code, :on => :create


  protected

  def generate_api_code
    self.api_code =  SecureRandom.hex(16)
  end


end

app/controllers/api/v1/logs_controller.rb
module Api
  module V1
    class LogsController < Api::V1::ApiController

      def create
        data = parse_post_params(params)
        @log_error = LogError.new(data)

        if @log_error.save
          handle_api_response @log_error.to_api_hash
        else
          handle_api_error(@log_error)
        end

      end

      protected

      def parse_post_params(params)
        data = {}
        data[:title] = params[:title] if params[:title].present?
        data[:data] = params[:data] if params[:data].present?
        data[:log_key] = params[:log_key] if params[:log_key].present?

        data
      end

    end
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @logs = Log.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logs }
    end
  end


  def show
    @log = Log.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @log }
    end
  end


  def new
    @log = Log.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @log }
    end
  end


  def edit
    @log = Log.find(params[:id])
  end


  def create
    @log = Log.new(params[:log])
    @log.user = current_user
    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render json: @log, status: :created, location: @log }
      else
        format.html { render action: "new" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @log = Log.find(params[:id])
    @log.user = current_user
    respond_to do |format|
      if @log.update_attributes(params[:log])
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @log = Log.find(params[:id])
    @log.destroy

    respond_to do |format|
      format.html { redirect_to logs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_for @log, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :key, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :key, :class => 'text_field' %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                logs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<%- model_class = Log -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/logs/index.html.erb
<%- model_class = Log -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:key) %></th>
      <th><%= model_class.human_attribute_name(:api_code) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= link_to log.id, log_path(log) %></td>
        <td><%= log._type %></td>
        <td><%= log._id %></td>
        <td><%= log.name %></td>
        <td><%= log.key %></td>
        <td><%= log.api_code %></td>
        <td><%= log.user_id %></td>
        <td><%=l log.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_log_path(log), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      log_path(log),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_log_path,
            :class => 'btn btn-primary' %>

app/views/logs/new.html.erb
<%- model_class = Log -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/logs/show.html.erb
<%- model_class = Log -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @log.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:key) %>:</strong></dt>
  <dd><%= @log.key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:api_code) %>:</strong></dt>
  <dd><%= @log.api_code %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              logs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_log_path(@log), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              log_path(@log),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>