config/routes.rb
Falgun::Application.routes.draw do

  resources :log_errors


  resources :logs


  devise_for :users

  root :to => "home#index"

  namespace :api do
    scope :module => 'v1', :constraints => ApiConstraints.new(:version => 1, :default => true) do
      resources :logs, :constraints => { :id => /.*/ }
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "FalgunApp" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Falgun App</a>

      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_url %></li>
          <li><%= link_to "Team", "/path2" %></li>
          <li><%= link_to "Features", "/path3" %></li>
          <li><%= link_to "Contact", "/path3" %></li>
          <% if user_signed_in? %>
              <li>
                <ul class="nav nav-pills">
                  <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Manage
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Create Log", new_log_url %></li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li><%= link_to "Log out", destroy_user_session_path  %></li>
          <% else %>
              <li class="divider"></li>
              <li><%= link_to "Sign in", new_user_session_url %></li>
              <li><%= link_to "Sign up", new_user_registration_url %></li>
          <% end %>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <div class="content">
    <div class="row">
      <div class="span9">
        <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
              <a class="close" data-dismiss="alert">&#215;</a>
              <div id="flash_#{name}">
                <%= msg.html_safe if msg.is_a?(String) %>
              </div>
            </div>
        <% end %>

        <%= yield %>
      </div>
      <div class="span3">
        <div class="well sidebar-nav">
          <h3>Sidebar</h3>
          <ul class="nav nav-list">
            <li class="nav-header">Sidebar</li>
            <li><%= link_to "Link1", "/path1" %></li>
            <li><%= link_to "Link2", "/path2" %></li>
            <li><%= link_to "Link3", "/path3" %></li>
          </ul>
        </div>
        <!--/.well -->
      </div>
      <!--/span-->
    </div>
    <!--/row-->
  </div>
  <!--/content-->

  <footer>
    <p>
      <a href="#about us">About us</a>
      <a href="#developers">Developers / API</a>
      <a href="#press">Press</a>
      <a href="#privacy">Privacy</a>
      <a href="#contact">Contact</a>
      <a href="#blog target=">Blog</a>
      © 2012 falgunapp. Crafted with love.</p>

  </footer>

</div>
<!-- /container -->

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>